cluster_name: my-cluster

# 分布式任务管理配置
task_spec:
  # 任务管理器版本
  version: "1.0"
  
  # 监控配置
  monitoring:
    grafana:
      port: 3000
    greptimedb:
      port: 4000
    enabled: true

# 节点列表
nodes:
  - ssh_url: "10.0.0.1:22"
    name: "head-node"  # 实际系统看到的节点名
    role: "head"
    workspace: "/opt/nokube-workspace"  # 工作空间根路径，所有资源文件将存储在此路径下
    storage:
      type: "local"
      path: "/data/ray/head"  # 相对于workspace的路径，实际: /opt/nokube-workspace/data/ray/head
    users:
      - userid: "your-username"
        password: "your-password"
    proxy:
      http_proxy: "http://proxy.example.com:8080"
      https_proxy: "http://proxy.example.com:8080"
      no_proxy: "localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16"

  - ssh_url: "10.0.0.2:22"
    name: "worker-node-1"   # 实际系统看到的节点名
    role: "worker"
    workspace: "/opt/nokube-workspace"  # 工作空间根路径
    storage:
      type: "local"
      path: "/data/ray/worker-1"  # 相对于workspace的路径，实际: /opt/nokube-workspace/data/ray/worker-1
    users:
      - userid: "your-username"
        password: "your-password"
    proxy:
      http_proxy: "http://proxy.example.com:8080"
      https_proxy: "http://proxy.example.com:8080"
      no_proxy: "localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16"

# NoKube 特定配置
nokube_config:
  # 日志配置
  log_level: "INFO"
  # 监控指标收集间隔(秒)
  metrics_interval: 30
  # 配置轮询间隔(秒)
  config_poll_interval: 10
