apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-config
  namespace: gitops-system
data:
  gitops-config.yaml: |
    # GitOps 配置（挂载至 /etc/gitops/gitops-config.yaml）
    github_configs:
      core-repo:
        repo_owner: "your-org"
        repo_name: "gitops-config"
        branch: "main"
        token: "ghp_your_token_here"

    services:
      - name: example
        github: core-repo
        k8s_yaml_dir: k8s

    # 可选：本地 Applyer（通过 nokube CLI 应用）
    applyer_nokube:
      cluster_name: "home-cluster"
      nokube_download_url: "https://releases.example.com/nokube/linux-amd64/nokube"

    poll_interval: 60

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-scripts
  namespace: gitops-system
data:
  requirements.txt: |
    requests==2.31.0
    PyYAML==6.0.1
  
  entrypoint.sh: |
    #!/bin/bash
    set -e
    
    echo "Installing Python dependencies..."
    pip install -r /scripts/requirements.txt
    
    echo "Starting GitOps controller..."
    python /scripts/gitops-controller.py

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gitops-controller
  namespace: nokube-system
  labels:
    app: gitops-controller
    component: automation
spec:
  selector:
    matchLabels:
      app: gitops-controller
  template:
    metadata:
      labels:
        app: gitops-controller
        component: automation
    spec:
      # 节点选择器 - 只在管理节点运行
      nodeSelector:
        role: management
      
      # 容忍管理节点的污点
      tolerations:
      - key: "node-role.gitops.io/management"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      containers:
      - name: gitops-controller
        image: python:3.10-slim
        
        # 启动命令
        command: ["/bin/bash"]
        args: ["/scripts/entrypoint.sh"]
        
        # 环境变量
        env:
        - name: PYTHONPATH
          value: "/scripts"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TZ
          value: "UTC"
        - name: GITOPS_CONFIG
          value: "/etc/gitops/gitops-config.yaml"
        
        # 资源限制
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # 挂载点
        volumeMounts:
        # GitOps脚本
        - name: scripts
          mountPath: /scripts
          readOnly: true
        
        # GitOps 配置（ConfigMap 挂载）
        - name: gitops-config
          mountPath: /etc/gitops
          readOnly: true
        
        # 工作空间（持久化状态和部署文件）
        - name: workspace
          mountPath: /pod-workspace
        
        # 健康检查
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ps aux | grep -v grep | grep gitops-controller.py"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "test -f /pod-workspace/gitops-state.json"
          initialDelaySeconds: 30
          periodSeconds: 10
      
      # 数据卷
      volumes:
      # GitOps脚本配置
      - name: scripts
        configMap:
          name: gitops-scripts
          defaultMode: 0755
          items:
          - key: gitops-controller.py
            path: gitops-controller.py
            mode: 0755
          - key: requirements.txt
            path: requirements.txt
          - key: entrypoint.sh
            path: entrypoint.sh
            mode: 0755
      
      # GitOps配置和密钥
      - name: gitops-config
        configMap:
          name: gitops-config
          defaultMode: 0444
      
      # 工作空间（使用主机路径持久化）
      - name: workspace
        hostPath:
          path: /opt/gitops-workspace
          type: DirectoryOrCreate
      
      # 重启策略
      restartPolicy: Always
      
      # 服务账号（如果需要访问k8s API）
      serviceAccountName: gitops-controller

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-controller
  namespace: gitops-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-controller
rules:
# 读取和创建资源的权限
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-controller
subjects:
- kind: ServiceAccount
  name: gitops-controller
  namespace: gitops-system
